### ISSUE TITLE
Switch to SQLlite

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/open-source-library-data-collector#9]

**Comment by georgeyk** [comment]
@thinkingserious I'll take this one for hacktoberfest, ok ?

**Comment by georgeyk** [comment]
Is there a problem to use `CLEARDB_DATABASE_URL` in local environments ?
I could change https://github.com/sendgrid/open-source-library-data-collector/blob/master/db_connector.py#L11-L33 to only handle "database urls".

This will also require to change env_sample to have something like this:
```
# local mysql
CLEARDB_DATABASE_URL=mysql://user:pass@127.0.0.1:/open-source-external-library-data
# local sqlite3 file
CLEARDB_DATABASE_URL=sqlite:///foo.db
# local sqlite3 in memory
CLEARDB_DATABASE_URL=sqlite://
```

I think this could be the first PR, since it does not need to support sqlite right away.

To proper support sqlite, `data_squema.sql` should be updated or a helper script to should create schema for sqlite (the drawback is to have another schema to maintain).

**Comment by thinkingserious** [comment]
@georgeyk,

I suggest `SQLLITE` or similar. CLEARDB is a MySQL DB provider that supports Heroku. The code should offer configuration that allows the user to specify which DB they would like to use.

I hope that helps!

With Best Regards,

Elmer

**Comment by georgeyk** [comment]
what about `DB_URL` ?
Generic and don't conflict with DATABASE_URL (heroku)

**Comment by thinkingserious** [comment]
I was thinking SQLLITE_DB, since a user may want to configure several databases for different needs. For example, perhaps someone would want a MONGO_DB to store certain types of data, SQLLITE_DB for other data and most data in MYSQL_DB.
